import WaterFullReport from "@/components/dashboard/analysisInput/AnalyzedAllviewDatails";
import React from "react";

const data = {
  success: true,
  message: "Report Successfully Analyzed!",
  data: {
    id: "69930a4069f305d70811042b",
    companyId: "69783f87ae022a74c2962e4f",
    createdAt: "2026-02-16T12:14:56.048Z",
    customer: {
      id: "698304a5a600ee7eabac50aa",
      name: "Enter ph",
      siteName: "site1",
      location: "Biocide",
      address: "e.g., 4500 Industrial Blvd",
      contactPerson: "Enter ph",
      contactEmail: "xyz@gmail.com",
      contactPhone: "052126262",
      isActive: true,
      companyId: "69783f87ae022a74c2962e4f",
      createdAt: "2026-02-04T08:34:45.367Z",
      updatedAt: "2026-02-04T08:34:45.367Z",
    },
    waterReport: {
      id: "69930a3e1ca6b97dfda961f7",
      report_id: "WQR-20260216-A1BC",
      sample_location: null,
      sample_date: null,
      original_filename: "manual_analysis",
      extracted_parameters: {
        pH: {
          value: 6.06,
          unit: "",
          detection_limit: null,
        },
        Total_Dissolved_Solids: {
          value: 11,
          unit: "mg/L",
          detection_limit: null,
        },
        Electrical_Conductivity: {
          value: 22,
          unit: "µS/cm",
          detection_limit: null,
        },
        Total_Hardness: {
          value: 75,
          unit: "mg/L",
          detection_limit: null,
        },
        Sulphate: {
          value: 5,
          unit: "mg/L",
          detection_limit: null,
        },
        Nitrate: {
          value: 0.13,
          unit: "mg/L",
          detection_limit: null,
        },
        Nitrite: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Fluoride: {
          value: 0.3,
          unit: "mg/L",
          detection_limit: null,
        },
        Arsenic: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Lead: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Cadmium: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Chromium: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Mercury: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Cyanide: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        Phenolic_Compounds: {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        E_coli: {
          value: 0,
          unit: "CFU/100mL",
          detection_limit: null,
        },
        "Calcium (Ca)": {
          value: 17,
          unit: "mg/L",
          detection_limit: null,
        },
        "Magnesium (Mg)": {
          value: 8,
          unit: "mg/L",
          detection_limit: null,
        },
        "Sodium (Na)": {
          value: 12,
          unit: "mg/L",
          detection_limit: null,
        },
        "Potassium (K)": {
          value: 2,
          unit: "mg/L",
          detection_limit: null,
        },
        "Chloride (Cl)": {
          value: 0,
          unit: "mg/L",
          detection_limit: null,
        },
        "Iron (Fe)": {
          value: 0.05,
          unit: "mg/L",
          detection_limit: null,
        },
        "Manganese (Mn)": {
          value: 0.02,
          unit: "mg/L",
          detection_limit: null,
        },
        "Total Coliform": {
          value: 0,
          unit: "CFU/100mL",
          detection_limit: null,
        },
      },
      parameter_graph: {
        graph_url:
          "https://water-analysis.s3.amazonaws.com/graphs/parameter_comparison_20260216_121340.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIARWF22OJOD2EMUHDH%2F20260216%2Feu-north-1%2Fs3%2Faws4_request&X-Amz-Date=20260216T121342Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=a0cd49b34cf005857a8806bfb36f34be9db6cb63f5368cf10060a9c7aa3dd489",
        graph_type: "parameter_comparison_bar",
        color_mapping: {
          pH: "warning",
          Total_Dissolved_Solids: "optimal",
          Electrical_Conductivity: "optimal",
          Total_Hardness: "good",
          Sulphate: "optimal",
          Nitrate: "optimal",
          Nitrite: "optimal",
          Fluoride: "optimal",
          Arsenic: "optimal",
          Lead: "optimal",
          Cadmium: "optimal",
          Chromium: "optimal",
          Mercury: "optimal",
          Cyanide: "optimal",
          Phenolic_Compounds: "optimal",
          E_coli: "optimal",
          "Calcium (Ca)": "optimal",
          "Magnesium (Mg)": "optimal",
          "Sodium (Na)": "optimal",
          "Potassium (K)": "optimal",
          "Chloride (Cl)": "optimal",
          "Iron (Fe)": "optimal",
          "Manganese (Mn)": "optimal",
          "Total Coliform": "optimal",
        },
        created_at: {
          $date: "2026-02-16T12:13:42.559Z",
        },
      },
      chemical_status: {
        input_parameters: {
          pH: {
            value: 6.06,
            unit: "",
            detection_limit: null,
          },
          Total_Dissolved_Solids: {
            value: 11,
            unit: "mg/L",
            detection_limit: null,
          },
          Electrical_Conductivity: {
            value: 22,
            unit: "µS/cm",
            detection_limit: null,
          },
          Total_Hardness: {
            value: 75,
            unit: "mg/L",
            detection_limit: null,
          },
          Sulphate: {
            value: 5,
            unit: "mg/L",
            detection_limit: null,
          },
          Nitrate: {
            value: 0.13,
            unit: "mg/L",
            detection_limit: null,
          },
          Nitrite: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Fluoride: {
            value: 0.3,
            unit: "mg/L",
            detection_limit: null,
          },
          Arsenic: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Lead: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Cadmium: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Chromium: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Mercury: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Cyanide: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          Phenolic_Compounds: {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          E_coli: {
            value: 0,
            unit: "CFU/100mL",
            detection_limit: null,
          },
          "Calcium (Ca)": {
            value: 17,
            unit: "mg/L",
            detection_limit: null,
          },
          "Magnesium (Mg)": {
            value: 8,
            unit: "mg/L",
            detection_limit: null,
          },
          "Sodium (Na)": {
            value: 12,
            unit: "mg/L",
            detection_limit: null,
          },
          "Potassium (K)": {
            value: 2,
            unit: "mg/L",
            detection_limit: null,
          },
          "Chloride (Cl)": {
            value: 0,
            unit: "mg/L",
            detection_limit: null,
          },
          "Iron (Fe)": {
            value: 0.05,
            unit: "mg/L",
            detection_limit: null,
          },
          "Manganese (Mn)": {
            value: 0.02,
            unit: "mg/L",
            detection_limit: null,
          },
          "Total Coliform": {
            value: 0,
            unit: "CFU/100mL",
            detection_limit: null,
          },
        },
        solution_parameters: {
          pH: 6.06,
          temperature: 25,
          ionic_strength: 4.416e-7,
          pe: null,
        },
        charge_balance_error: 0,
        saturation_indices: [],
        ionic_strength: 4.416e-7,
        database_used: "phreeqc.dat",
        molalities: {},
        equilibrium_phases: {},
        electrical_balance: 8.6e-7,
      },
      total_score: {
        overall_score: 73.4,
        max_score: 100,
        rating: "Fair",
        components: [
          {
            name: "Chemical Parameters",
            score: 60,
            max_score: 100,
            weight: 0.4,
          },
          {
            name: "Biological Indicators",
            score: 100,
            max_score: 100,
            weight: 0.3,
          },
          {
            name: "Compliance",
            score: 91.9,
            max_score: 100,
            weight: 0.2,
          },
          {
            name: "Risk Assessment",
            score: 10,
            max_score: 100,
            weight: 0.1,
          },
        ],
      },
      quality_report: {
        water_quality_index: {
          score: 50,
          max_score: 100,
          rating: "Fair",
        },
        compliance_score: {
          score: 91.9,
          percentage: "91.9%",
          rating: "Very Good",
        },
        risk_factor: {
          score: 9.5,
          max_score: 10,
          severity: "Critical Risk",
        },
      },
      chemical_composition: {
        parameters: [
          {
            parameter_name: "pH",
            value: 6.06,
            unit: "",
            status: "unknown",
            threshold: null,
            chemical_symbol: "pH",
            chemical_formula: "-log[H⁺]",
            ionic_form: "H+",
            as_compound: null,
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "physical",
          },
          {
            parameter_name: "Total_Dissolved_Solids",
            value: 11,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "TDS",
            chemical_formula: "Total Dissolved Solids",
            ionic_form: null,
            as_compound: null,
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "physical",
          },
          {
            parameter_name: "Electrical_Conductivity",
            value: 22,
            unit: "µS/cm",
            status: "unknown",
            threshold: null,
            chemical_symbol: "EC",
            chemical_formula: "Electrical Conductivity",
            ionic_form: null,
            as_compound: null,
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "physical",
          },
          {
            parameter_name: "Total_Hardness",
            value: 75,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Hardness",
            chemical_formula: "Total Hardness as CaCO₃",
            ionic_form: null,
            as_compound: "CaCO₃",
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "physical",
          },
          {
            parameter_name: "Sulphate",
            value: 5,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "SO₄",
            chemical_formula: "SO₄²⁻",
            ionic_form: "SO4-2",
            as_compound: "Na₂SO₄",
            as_compound_value: null,
            molecular_weight: 96.06,
            charge: -2,
            category: "major_anion",
          },
          {
            parameter_name: "Nitrate",
            value: 0.13,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "NO₃",
            chemical_formula: "NO₃⁻",
            ionic_form: "NO3-",
            as_compound: "NaNO₃",
            as_compound_value: null,
            molecular_weight: 62.004,
            charge: -1,
            category: "major_anion",
          },
          {
            parameter_name: "Nitrite",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "NO₂",
            chemical_formula: "NO₂⁻",
            ionic_form: "NO2-",
            as_compound: "NaNO₂",
            as_compound_value: null,
            molecular_weight: 46.005,
            charge: -1,
            category: "major_anion",
          },
          {
            parameter_name: "Fluoride",
            value: 0.3,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "F",
            chemical_formula: "F⁻",
            ionic_form: "F-",
            as_compound: "NaF",
            as_compound_value: null,
            molecular_weight: 18.998,
            charge: -1,
            category: "major_anion",
          },
          {
            parameter_name: "Arsenic",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "As",
            chemical_formula: "As³⁺/As⁵⁺",
            ionic_form: "As3+",
            as_compound: "As₂O₃",
            as_compound_value: null,
            molecular_weight: 74.922,
            charge: 3,
            category: "heavy_metal",
          },
          {
            parameter_name: "Lead",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Pb",
            chemical_formula: "Pb²⁺",
            ionic_form: "Pb2+",
            as_compound: "PbO",
            as_compound_value: null,
            molecular_weight: 207.2,
            charge: 2,
            category: "heavy_metal",
          },
          {
            parameter_name: "Cadmium",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Cd",
            chemical_formula: "Cd²⁺",
            ionic_form: "Cd2+",
            as_compound: "CdO",
            as_compound_value: null,
            molecular_weight: 112.411,
            charge: 2,
            category: "heavy_metal",
          },
          {
            parameter_name: "Chromium",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Cr",
            chemical_formula: "Cr³⁺/Cr⁶⁺",
            ionic_form: "Cr3+",
            as_compound: "Cr₂O₃",
            as_compound_value: null,
            molecular_weight: 51.996,
            charge: 3,
            category: "heavy_metal",
          },
          {
            parameter_name: "Mercury",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Hg",
            chemical_formula: "Hg²⁺",
            ionic_form: "Hg2+",
            as_compound: "HgO",
            as_compound_value: null,
            molecular_weight: 200.59,
            charge: 2,
            category: "heavy_metal",
          },
          {
            parameter_name: "Cyanide",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "CN",
            chemical_formula: "CN⁻",
            ionic_form: "CN-",
            as_compound: "NaCN",
            as_compound_value: null,
            molecular_weight: 26.017,
            charge: -1,
            category: "toxic",
          },
          {
            parameter_name: "Phenolic_Compounds",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "C₆H₅OH",
            chemical_formula: "C₆H₅OH",
            ionic_form: null,
            as_compound: "Phenol",
            as_compound_value: null,
            molecular_weight: 94.11,
            charge: 0,
            category: "organic",
          },
          {
            parameter_name: "E_coli",
            value: 0,
            unit: "CFU/100mL",
            status: "unknown",
            threshold: null,
            chemical_symbol: "E_coli",
            chemical_formula: null,
            ionic_form: null,
            as_compound: null,
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "biological",
          },
          {
            parameter_name: "Calcium (Ca)",
            value: 17,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Ca",
            chemical_formula: "Ca²⁺",
            ionic_form: "Ca2+",
            as_compound: "CaCO₃",
            as_compound_value: null,
            molecular_weight: 40.078,
            charge: 2,
            category: "major_cation",
          },
          {
            parameter_name: "Magnesium (Mg)",
            value: 8,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Mg",
            chemical_formula: "Mg²⁺",
            ionic_form: "Mg2+",
            as_compound: "MgCO₃",
            as_compound_value: null,
            molecular_weight: 24.305,
            charge: 2,
            category: "major_cation",
          },
          {
            parameter_name: "Sodium (Na)",
            value: 12,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Na",
            chemical_formula: "Na⁺",
            ionic_form: "Na+",
            as_compound: "NaCl",
            as_compound_value: null,
            molecular_weight: 22.99,
            charge: 1,
            category: "major_cation",
          },
          {
            parameter_name: "Potassium (K)",
            value: 2,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "K",
            chemical_formula: "K⁺",
            ionic_form: "K+",
            as_compound: "KCl",
            as_compound_value: null,
            molecular_weight: 39.098,
            charge: 1,
            category: "major_cation",
          },
          {
            parameter_name: "Chloride (Cl)",
            value: 0,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Cl",
            chemical_formula: "Cl⁻",
            ionic_form: "Cl-",
            as_compound: "NaCl",
            as_compound_value: null,
            molecular_weight: 35.453,
            charge: -1,
            category: "major_anion",
          },
          {
            parameter_name: "Iron (Fe)",
            value: 0.05,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Fe",
            chemical_formula: "Fe²⁺/Fe³⁺",
            ionic_form: "Fe2+",
            as_compound: "Fe₂O₃",
            as_compound_value: null,
            molecular_weight: 55.845,
            charge: 2,
            category: "heavy_metal",
          },
          {
            parameter_name: "Manganese (Mn)",
            value: 0.02,
            unit: "mg/L",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Mn",
            chemical_formula: "Mn²⁺",
            ionic_form: "Mn2+",
            as_compound: "MnO₂",
            as_compound_value: null,
            molecular_weight: 54.938,
            charge: 2,
            category: "heavy_metal",
          },
          {
            parameter_name: "Total Coliform",
            value: 0,
            unit: "CFU/100mL",
            status: "unknown",
            threshold: null,
            chemical_symbol: "Total_Coliform",
            chemical_formula: null,
            ionic_form: null,
            as_compound: null,
            as_compound_value: null,
            molecular_weight: null,
            charge: 0,
            category: "biological",
          },
        ],
        summary:
          "Detected 4 major cation, 5 major anion, 7 heavy metal, 4 physical, 2 biological, 1 organic parameters.",
      },
      biological_indicators: {
        indicators: [
          {
            indicator_name: "Total Coliform",
            value: 0,
            unit: "CFU/100mL",
            status: "Safe",
            risk_level: "Low",
          },
        ],
        overall_status: "Safe",
      },
      compliance_checklist: {
        items: [
          {
            parameter: "pH",
            standard: "WHO",
            status: "Failed",
            actual_value: 6.06,
            required_value: "6.5-8.5",
            unit: "",
            remarks: "Below minimum (6.5)",
          },
          {
            parameter: "pH",
            standard: "Bangladesh",
            status: "Failed",
            actual_value: 6.06,
            required_value: "6.5-8.5",
            unit: "",
            remarks: "Below minimum (6.5)",
          },
          {
            parameter: "TDS",
            standard: "WHO",
            status: "Passed",
            actual_value: 11,
            required_value: "≤ 500",
            unit: "mg/L",
            remarks: "Below maximum limit (500)",
          },
          {
            parameter: "TDS",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 11,
            required_value: "≤ 1000",
            unit: "mg/L",
            remarks: "Below maximum limit (1000)",
          },
          {
            parameter: "Arsenic",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.01",
            unit: "mg/L",
            remarks: "Below maximum limit (0.01)",
          },
          {
            parameter: "Arsenic",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.05",
            unit: "mg/L",
            remarks: "Below maximum limit (0.05)",
          },
          {
            parameter: "Lead",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.01",
            unit: "mg/L",
            remarks: "Below maximum limit (0.01)",
          },
          {
            parameter: "Lead",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.05",
            unit: "mg/L",
            remarks: "Below maximum limit (0.05)",
          },
          {
            parameter: "Cadmium",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.003",
            unit: "mg/L",
            remarks: "Below maximum limit (0.003)",
          },
          {
            parameter: "Cadmium",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.005",
            unit: "mg/L",
            remarks: "Below maximum limit (0.005)",
          },
          {
            parameter: "Chromium",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.05",
            unit: "mg/L",
            remarks: "Below maximum limit (0.05)",
          },
          {
            parameter: "Mercury",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.001",
            unit: "mg/L",
            remarks: "Below maximum limit (0.001)",
          },
          {
            parameter: "Mercury",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.001",
            unit: "mg/L",
            remarks: "Below maximum limit (0.001)",
          },
          {
            parameter: "Nitrate",
            standard: "WHO",
            status: "Passed",
            actual_value: 0.13,
            required_value: "≤ 50",
            unit: "mg/L",
            remarks: "Below maximum limit (50)",
          },
          {
            parameter: "Nitrate",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0.13,
            required_value: "≤ 10",
            unit: "mg/L",
            remarks: "Below maximum limit (10)",
          },
          {
            parameter: "Nitrite",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 3",
            unit: "mg/L",
            remarks: "Below maximum limit (3)",
          },
          {
            parameter: "Nitrite",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 1",
            unit: "mg/L",
            remarks: "Below maximum limit (1)",
          },
          {
            parameter: "Chloride",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 250",
            unit: "mg/L",
            remarks: "Below maximum limit (250)",
          },
          {
            parameter: "Chloride",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 150",
            unit: "mg/L",
            remarks: "Below maximum limit (150)",
          },
          {
            parameter: "Sulfate",
            standard: "WHO",
            status: "Passed",
            actual_value: 5,
            required_value: "≤ 250",
            unit: "mg/L",
            remarks: "Below maximum limit (250)",
          },
          {
            parameter: "Sulfate",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 5,
            required_value: "≤ 400",
            unit: "mg/L",
            remarks: "Below maximum limit (400)",
          },
          {
            parameter: "Calcium",
            standard: "WHO",
            status: "Failed",
            actual_value: 17,
            required_value: "20-75",
            unit: "mg/L",
            remarks: "Below minimum (20)",
          },
          {
            parameter: "Magnesium",
            standard: "WHO",
            status: "Passed",
            actual_value: 8,
            required_value: "≤ 50",
            unit: "mg/L",
            remarks: "Below maximum limit (50)",
          },
          {
            parameter: "Sodium",
            standard: "WHO",
            status: "Passed",
            actual_value: 12,
            required_value: "≤ 200",
            unit: "mg/L",
            remarks: "Below maximum limit (200)",
          },
          {
            parameter: "Chlorine",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "0.2-5",
            unit: "mg/L",
            remarks: "Not tested",
          },
          {
            parameter: "Chlorine",
            standard: "Bangladesh",
            status: "Pending",
            actual_value: null,
            required_value: "0.2-2",
            unit: "mg/L",
            remarks: "Not tested",
          },
          {
            parameter: "Cyanide",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0.07",
            unit: "mg/L",
            remarks: "Below maximum limit (0.07)",
          },
          {
            parameter: "Fluoride",
            standard: "WHO",
            status: "Passed",
            actual_value: 0.3,
            required_value: "≤ 1.5",
            unit: "mg/L",
            remarks: "Below maximum limit (1.5)",
          },
          {
            parameter: "Fluoride",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0.3,
            required_value: "≤ 1",
            unit: "mg/L",
            remarks: "Below maximum limit (1)",
          },
          {
            parameter: "Iron",
            standard: "WHO",
            status: "Passed",
            actual_value: 0.05,
            required_value: "≤ 0.3",
            unit: "mg/L",
            remarks: "Below maximum limit (0.3)",
          },
          {
            parameter: "Iron",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0.05,
            required_value: "≤ 0.3",
            unit: "mg/L",
            remarks: "Below maximum limit (0.3)",
          },
          {
            parameter: "Manganese",
            standard: "WHO",
            status: "Passed",
            actual_value: 0.02,
            required_value: "≤ 0.1",
            unit: "mg/L",
            remarks: "Below maximum limit (0.1)",
          },
          {
            parameter: "Manganese",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0.02,
            required_value: "≤ 0.1",
            unit: "mg/L",
            remarks: "Below maximum limit (0.1)",
          },
          {
            parameter: "Turbidity",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 5",
            unit: "NTU",
            remarks: "Not tested",
          },
          {
            parameter: "Turbidity",
            standard: "Bangladesh",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 10",
            unit: "NTU",
            remarks: "Not tested",
          },
          {
            parameter: "Hardness",
            standard: "WHO",
            status: "Passed",
            actual_value: 75,
            required_value: "≤ 500",
            unit: "mg/L as CaCO3",
            remarks: "Below maximum limit (500)",
          },
          {
            parameter: "E.coli",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0",
            unit: "CFU/100ml",
            remarks: "Below maximum limit (0)",
          },
          {
            parameter: "E.coli",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0",
            unit: "CFU/100ml",
            remarks: "Below maximum limit (0)",
          },
          {
            parameter: "Total Coliform",
            standard: "WHO",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0",
            unit: "CFU/100ml",
            remarks: "Below maximum limit (0)",
          },
          {
            parameter: "Total Coliform",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0",
            unit: "CFU/100ml",
            remarks: "Below maximum limit (0)",
          },
          {
            parameter: "Fecal Coliform",
            standard: "Bangladesh",
            status: "Passed",
            actual_value: 0,
            required_value: "≤ 0",
            unit: "CFU/100ml",
            remarks: "Below maximum limit (0)",
          },
          {
            parameter: "Aluminum",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 0.2",
            unit: "mg/L",
            remarks: "Not tested",
          },
          {
            parameter: "Copper",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 2",
            unit: "mg/L",
            remarks: "Not tested",
          },
          {
            parameter: "Zinc",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 3",
            unit: "mg/L",
            remarks: "Not tested",
          },
          {
            parameter: "Ammonia",
            standard: "WHO",
            status: "Pending",
            actual_value: null,
            required_value: "≤ 1.5",
            unit: "mg/L",
            remarks: "Not tested",
          },
        ],
        overall_compliance: 91.9,
        passed_count: 34,
        failed_count: 3,
        pending_count: 8,
        total_rules: 45,
      },
      contamination_risk: {
        heavy_metals: [
          {
            contaminant_name: "Total_Dissolved_Solids",
            value: 11,
            unit: "mg/L",
            risk_level: "Critical",
            threshold: 0.1,
          },
          {
            contaminant_name: "Arsenic",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.001,
          },
          {
            contaminant_name: "Lead",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.001,
          },
          {
            contaminant_name: "Cadmium",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.001,
          },
          {
            contaminant_name: "Chromium",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.01,
          },
          {
            contaminant_name: "Mercury",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.0001,
          },
          {
            contaminant_name: "Cyanide",
            value: 0,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.01,
          },
          {
            contaminant_name: "Iron (Fe)",
            value: 0.05,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.1,
          },
          {
            contaminant_name: "Manganese (Mn)",
            value: 0.02,
            unit: "mg/L",
            risk_level: "Low",
            threshold: 0.05,
          },
          {
            contaminant_name: "Total Coliform",
            value: 0,
            unit: "CFU/100mL",
            risk_level: "Low",
            threshold: 0,
          },
        ],
        organic_compounds: [],
        microbiological: [
          {
            contaminant_name: "E_coli",
            value: 0,
            unit: "CFU/100mL",
            risk_level: "Low",
            threshold: 0,
          },
          {
            contaminant_name: "Total Coliform",
            value: 0,
            unit: "CFU/100mL",
            risk_level: "Low",
            threshold: 0,
          },
        ],
        overall_severity: "Critical",
        contamination_score: 1.8,
        risk_score: 1.8,
        score_explanation:
          "contamination_score: 0=safe, 10=critical (inverse of water quality score)",
      },
      created_at: "2026-02-16T12:14:54.978Z",
      updated_at: "2026-02-16T12:14:54.978Z",
    },
  },
};

const page = () => {
  return (
    <div>
      <WaterFullReport data={data} />
    </div>
  );
};

export default page;
