import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Toaster } from "sonner";
import ReduxProvider from "@/redux/Provider";
import Loading from "@/components/Others/Loading";
import { GoogleOAuthProvider } from "@react-oauth/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Jimgreen81",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={dmSans.variable}>
        <div className="bg-[#FFFFFF]">
          <GoogleOAuthProvider
            clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ""}
          >
            <ReduxProvider>
              <Toaster position="top-center" expand={true} richColors />
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </ReduxProvider>
          </GoogleOAuthProvider>
        </div>
      </body>
    </html>
  );
}
